"""Reviewer node - self-reviews code changes for quality."""

from __future__ import annotations

import json
import logging
import time
from typing import Any

from agent.state import AgentState, TaskStatus
from app.events import event_bus
from llm.provider import ModelTier, llm
from tools.git_ops import get_diff

logger = logging.getLogger(__name__)

STEP_NAME = "Reviewer"

REVIEWER_SYSTEM_PROMPT = """You are a senior code reviewer. Review the changes made by a coding agent and decide if they are ready to be submitted as a pull request.

Check for:
1. **Correctness** - Do the changes actually solve the issue?
2. **Code quality** - Clean code, proper naming, no dead code
3. **Edge cases** - Are edge cases handled?
4. **Style** - Consistent with the project's code style
5. **Security** - No obvious security issues
6. **Documentation** - Are changes documented?

Respond in JSON format:
{
    "approved": true/false,
    "feedback": "Detailed feedback...",
    "issues": ["list of specific issues to fix"],
    "pr_title": "Suggested PR title",
    "pr_body": "Suggested PR description in markdown"
}

If approved is false, the coder agent will attempt to fix the issues you identify.
Only reject if there are real problems - don't be overly pedantic."""


async def reviewer_node(state: AgentState) -> dict[str, Any]:
    """Self-review the code changes.

    Reads: workspace_path, implementation_plan, code_changes, test_results
    Writes: review_feedback, review_approved, pr_title, pr_body, status
    """
    workspace = state.get("workspace_path", "")
    task_id = state.get("task_id", "")
    started = time.time()

    logger.info("[Reviewer] Starting self-review")
    event_bus.step_start(task_id, STEP_NAME)
    event_bus.emit(task_id, STEP_NAME, "Starting self-review", "info")

    # Get the diff of all changes
    diff_result = await get_diff(workspace)
    diff = diff_result.get("diff", "No diff available")

    messages = [
        {"role": "system", "content": REVIEWER_SYSTEM_PROMPT},
        {
            "role": "user",
            "content": f"""Review these code changes:

**Issue:** {state.get('issue_title', 'No title')}
**Classification:** {state.get('task_classification', 'unknown')}

**Implementation Plan:**
{state.get('implementation_plan', 'No plan')[:2000]}

**Test Results:**
{'All tests passed' if state.get('test_results', {}).get('passed') else 'Tests had issues'}

**Code Diff:**
```diff
{diff[:5000]}
```

Review and provide your assessment.""",
        },
    ]

    response = await llm.chat(messages=messages, tier=ModelTier.STANDARD, temperature=0.1)

    # Parse review
    try:
        clean = response.strip()
        if "```json" in clean:
            start = clean.index("```json") + 7
            end = clean.index("```", start)
            clean = clean[start:end].strip()
        elif "```" in clean:
            parts = clean.split("```")
            for part in parts[1::2]:
                stripped = part.strip()
                if stripped.startswith("json"):
                    stripped = stripped[4:].strip()
                if stripped.startswith("{"):
                    clean = stripped
                    break

        review = json.loads(clean)
    except (json.JSONDecodeError, ValueError):
        # If parsing fails, approve (let human reviewer catch issues)
        review = {
            "approved": True,
            "feedback": response,
            "pr_title": f"Fix: {state.get('issue_title', 'Issue')}",
            "pr_body": response,
        }

    approved = review.get("approved", False)
    feedback = review.get("feedback", "")
    review_retry_count = state.get("review_retry_count", 0)

    # Cap the reviewer->coder revision loop so we can't spin forever
    if not approved:
        review_retry_count += 1
        max_review_retries = state.get("max_retries", 3)
        if review_retry_count >= max_review_retries:
            logger.warning(
                f"[Reviewer] Max review revisions ({max_review_retries}) reached - proceeding to PR"
            )
            event_bus.emit(
                task_id,
                STEP_NAME,
                f"Max revisions ({max_review_retries}) reached - proceeding to PR anyway",
                "warning",
            )
            approved = True

    verdict = "Approved" if approved else "Rejected"
    logger.info(f"[Reviewer] {verdict}")
    event_bus.emit(task_id, STEP_NAME, verdict, "success" if approved else "warning")

    duration = time.time() - started

    if approved:
        # Generate PR title and body
        issue_num = state.get("issue_number", "")
        pr_title = review.get("pr_title", f"Fix #{issue_num}: {state.get('issue_title', 'Issue')}")
        pr_body = review.get(
            "pr_body",
            f"## Changes\n\nResolves #{issue_num}\n\n{feedback}",
        )

        # Add auto-generated footer
        pr_body += "\n\n---\n*This PR was automatically generated by Vegapunk.*"

        event_bus.step_end(task_id, STEP_NAME, "success", duration)

        return {
            "review_feedback": feedback,
            "review_approved": True,
            "review_retry_count": review_retry_count,
            "pr_title": pr_title,
            "pr_body": pr_body,
            "status": TaskStatus.CREATING_PR,
            "current_step": "Review approved - creating pull request",
            "messages": [{"role": "assistant", "content": f"Review approved: {feedback}"}],
        }
    else:
        issues = review.get("issues", [])
        issue_text = "\n".join(f"- {issue}" for issue in issues) if issues else feedback

        event_bus.step_end(task_id, STEP_NAME, "warning", duration)

        return {
            "review_feedback": issue_text,
            "review_approved": False,
            "review_retry_count": review_retry_count,
            "status": TaskStatus.CODING,
            "current_step": f"Review found issues - sending back to coder (revision {review_retry_count})",
            "messages": [
                {"role": "assistant", "content": f"Review issues:\n{issue_text}"}
            ],
        }
